logging:
    level:
        ru.yandex.practicum: trace
        org.zalando.logbook: TRACE

#server:
#    port: 8081
#
spring:
    sql:
        init:
            mode: always
    datasource:
        url: jdbc:h2:file:./db/filmorate
        driver-class-name: org.h2.Driver
        username: sa
        password: password
